services:
  #servertest:
  #  image: servertest
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  depends_on:
  #    db:
  #      condition: service_healthy
  db:
    container_name: postgres
    image: postgres:14.13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PW}
    ports:
      - "5050:80"
    restart: always